config/routes.rb
Rails.application.routes.draw do
  root to: "tools#index"
  resources :tools
  resources :users, only: [:index, :new, :create, :show] do
    resources :tools, only: [:show]
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools

  validates :name, presence: true
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :name,
            :quantity,
            :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :tools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:alert] = "Welcome back!"
      redirect_to user_path(@user)
    else
      flash[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  # helper_method :tool_chest_not_empty?, :most_recent_tool
  before_action :set_tool, only: [:show, :destroy]

  def index
    # cookies[:hit_counter] = cookies[:hit_counter].to_i + 1
    session[:hit_counter] = session[:hit_counter].to_i + 1
    if session[:hit_counter].to_i.even?
      flash[:alert] = "Hit counter is even!"
    else
      flash[:alert] = "Hit counter is odd"
    end
    # session[:most_recent_tool_id] = Tool.last.id
    @tools = Tool.all
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    @category = @tool.category
    if @tool.save
      redirect_to tool_path(@tool.id) 
      flash[:notice] = "Success!"
    else
      render :new
      flash[:error] = @tool.error.full_messages.join(", ")
    end
  end

  def show
  end

  def destroy
    tool.destroy
    redirect_to tools_path # represents index page, can't send back to tool specific page since it has been deleted
  end

  private

  def tool_params # typically named as 'singular entity_params'
    params.require(:tool).permit(:name, :price, :quantity, :category_id)
    # params.require(:tool) => accesses sub hash key-value pair
    # permitting only three attributes to be submitted
  end

  def set_tool
    @tool = Tool.find(params[:id])
  end

  # def most_recent_tool
  #   Tool.find(session[:most_recent_tool_id]).name
  # end
  #
  # def tool_chest_not_empty?
  #   @tools != nil
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
      flash[:notice] = "Welcome, #{@user.name}!"
    else
      render :new
      flash[:error] = @user.errors.full_messages.join(", ")
    end
  end

  def show
    @user = User.find(params[:id])
    @tools = @user.tools
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="gateway">
    <% if current_user  %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash_#{type}" %>
  <% end %>

  <br>

  <strong>Visits:</strong> <%= session[:hit_counter] %>

  <%= yield %>

</body>
</html>

app/views/tools/index.html.erb
<h1> All Tools </h1>

<%= link_to "Create New Tool", new_tool_path %>

<ul>
<% @tools.each do |tool| %>
  <li>
    <%= link_to "#{tool.name}", tool_path(tool.id) %> - <%= tool.quantity %>
  </li>
<% end %>
</ul>

app/views/tools/new.html.erb
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.all, :id, :name %>

  <%= f.submit%>
<% end %>

app/views/tools/show.html.erb
<div class="tool_info">

  <h3> <%= @tool.name %> </h3>
  <ul>
    <li> Price: <%= @tool.price %> </li>
    <li> Quantity: <%= @tool.quantity %> </li>
    <li> Category: <%= @tool.category.name %>  </li>
  </ul>

</div>

<%= link_to "Delete", tool_path(@tool), method: :delete, data: {confirm: "Really delete the article?"} %>
<br><br>

<p>
  <%= link_to "<< Return to Tools Index", tools_path %>
</p>

app/views/users/new.html.erb
<h1> Create a new account </h1>

<div class="registration">

  <%= form_for(@user) do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>

  <%= f.text_field :email, placeholder: "Email"  %>

  <%= f.text_field :username, placeholder: "Username"  %>

  <%= f.password_field :password, placeholder: "Password"  %>

  <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1> Tools of <%= @user.name %> </h1>

<table id="user_tools">
  <tr>
    <td><b>Tool</b></td>
    <td><b>Quantity</b></td>
    <td><b>Price</b></td>
    <td><b>Category</b></td>
    <td><b>Tool Details</b></td>
  </tr>
  <% @tools.each do |tool| %>
  <tr>
    <td><%= tool.name %></td>
    <td><%= tool.quantity %></td>
    <td><%= tool.price %></td>
    <td><%= tool.category.name %></td>
    <td> <%= link_to "#{tool.name} Deets", user_tool_path(@user.id, tool.id)%> </td>
  </tr>
  <% end %>
</table>